In [1]:
import numpy, sympy
from sympy import N
from loom.sage_subprocess import solve_poly_system
x, z = sympy.symbols('x z')

Use TkAgg backend for matplotlib.


In [41]:
f = sympy.sympify('x**6 - 10*x**2*z + 4*x + 9*z**2')

In [42]:
f.diff(x)

6*x**5 - 20*x*z + 4

In [43]:
poly_system = [f, f.diff(x)]

In [7]:
sols_sage = numpy.array(solve_poly_system(poly_system))

In [7]:
#sols_sympy = sympy.solve_poly_system([f, f.diff(x)], z, x)

In [8]:
#sols_sympy_N = numpy.array([[complex(z), complex(x)] for z, x in sols_sympy])

In [25]:
sols_sage

array([[ 0.17272260-0.29916432j,  0.25229196+0.43698248j],
       [ 0.17272260+0.29916432j,  0.25229196-0.43698248j],
       [-0.34544520+0.j        , -0.50458392+0.j        ],
       [-0.32876426-0.56943641j, -0.81798269+1.41678759j],
       [-0.32876426+0.56943641j, -0.81798269-1.41678759j],
       [ 0.65752847+0.j        ,  1.63596539+0.j        ]])

In [24]:
#sols_sympy_N

array([[-0.34544520+0.j        , -0.50458391+0.j        ],
       [ 0.17272260+0.29916432j,  0.25229196-0.43698248j],
       [ 0.17272260-0.29916432j,  0.25229196+0.43698248j],
       [ 0.65752853+0.j        ,  1.63596539+0.j        ],
       [-0.32876426+0.56943641j, -0.81798269-1.41678759j],
       [-0.32876426-0.56943641j, -0.81798269+1.41678759j]])

In [29]:
#sols_sage[0] - sols_sympy_N[2]

array([  5.55111512e-17+0.j,  -5.55111512e-17+0.j])

In [30]:
#sols_sage[1] - sols_sympy_N[1]

array([  5.55111512e-17+0.j,  -5.55111512e-17+0.j])

In [31]:
#sols_sage[2] - sols_sympy_N[0]

array([  5.02952219e-09+0.j,  -1.10148788e-08+0.j])

In [32]:
#sols_sage[3] - sols_sympy_N[5]

array([  5.55111512e-17 +1.11022302e-16j,  -1.11022302e-16 +2.22044605e-16j])

In [33]:
#sols_sage[4] - sols_sympy_N[4]

array([  5.55111512e-17 -1.11022302e-16j,  -1.11022302e-16 -2.22044605e-16j])

In [34]:
#sols_sage[5] - sols_sympy_N[3]

array([ -5.64597031e-08+0.j,   4.37893100e-09+0.j])

In [24]:
z_0, x_0 = sols_sage[2]
z_0, x_0

((-0.34544519667495072+0j), (-0.50458392101551486+0j))

In [11]:
fx_at_z_0 = f.subs(z, z_0)

In [12]:
fx_at_z_0

x**4 + 3.45445196674951*x**2 + 4*x + 1.07399145515216

In [13]:
fx_at_z_0_coeffs = map(complex, sympy.Poly(fx_at_z_0, x).all_coeffs())

In [14]:
fx_at_z_0_coeffs

[(1+0j), 0j, (3.4544519667495073+0j), (4+0j), (1.0739914551521585+0j)]

In [17]:
roots1 = numpy.roots(fx_at_z_0_coeffs)

In [19]:
roots1

array([ 0.50458391 +1.99089473e+00j,  0.50458391 -1.99089473e+00j,
       -0.50467797 +3.64711943e-14j, -0.50448985 -3.64506392e-14j])

In [26]:
numpy.array([x_0]*4) - roots1

array([ -1.00916783e+00 -1.99089473e+00j,
        -1.00916783e+00 +1.99089473e+00j,
         9.40535241e-05 -3.64711943e-14j,  -9.40689503e-05 +3.64506392e-14j])

In [44]:
sols_sympy = sympy.solve_poly_system([f, f.diff(x)], z, x)

In [27]:
z_0, x_0 = sols_sympy[0]

In [28]:
fx_at_z_0 = f.subs(z, z_0)

In [29]:
fx_at_z_0

x**4 + 5*x**2*(-17 + 5*sqrt(13))**(2/3)*(5 + 2*sqrt(13))/18 + 4*x + (-17 + 5*sqrt(13))**(4/3)*(5 + 2*sqrt(13))**2/144

In [30]:
fx_at_z_0_coeffs = map(complex, sympy.Poly(fx_at_z_0, x).all_coeffs())

In [31]:
fx_at_z_0_coeffs

[(1+0j), 0j, (3.454452017044729+0j), (4+0j), (1.0739914864257956+0j)]

In [32]:
roots2 = numpy.roots(fx_at_z_0_coeffs)

In [33]:
roots2

array([ 0.50458391 +1.99089474e+00j,  0.50458391 -1.99089474e+00j,
       -0.50458389 -3.84091993e-10j, -0.50458393 +3.84091920e-10j])

In [35]:
numpy.array([complex(x_0)]*4) - roots2

array([ -1.00916782e+00 -1.99089474e+00j,
        -1.00916782e+00 +1.99089474e+00j,
        -1.52167814e-08 +3.84091993e-10j,   1.52167827e-08 -3.84091920e-10j])

In [36]:
sols_sympy = sympy.solve([f, f.diff(x)], z, x)

In [37]:
sols_sympy

[(-(-17 + 5*sqrt(13))**(2/3)*(5 + 2*sqrt(13))/36,
  -(-17 + 5*sqrt(13))**(1/3)/2),
 ((-17 + 5*sqrt(13))**(2/3)*(5 + 2*sqrt(13) + 5*sqrt(3)*I + 2*sqrt(39)*I)/72,
  (-17 + 5*sqrt(13))**(1/3)*(1 - sqrt(3)*I)/4),
 ((-17 + 5*sqrt(13))**(2/3)*(5 + 2*sqrt(13) - 2*sqrt(39)*I - 5*sqrt(3)*I)/72,
  (-17 + 5*sqrt(13))**(1/3)*(1 + sqrt(3)*I)/4),
 ((-5 + 2*sqrt(13))*(17 + 5*sqrt(13))**(2/3)/36, (17 + 5*sqrt(13))**(1/3)/2),
 ((17 + 5*sqrt(13))**(2/3)*(-2*sqrt(13) + 5 - 5*sqrt(3)*I + 2*sqrt(39)*I)/72,
  -(1 + sqrt(3)*I)*(17 + 5*sqrt(13))**(1/3)/4),
 ((17 + 5*sqrt(13))**(2/3)*(-2*sqrt(13) + 5 - 2*sqrt(39)*I + 5*sqrt(3)*I)/72,
  (-1 + sqrt(3)*I)*(17 + 5*sqrt(13))**(1/3)/4)]